# -*- coding: utf-8 -*-
"""MultipleLinearRegressionProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EXQ10K02LAc_63qN3FKKoudmvaO7w89n
"""

from google.colab import drive
drive.mount('/content/drive')

"""#Import Libraries#"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""#Import Data#"""

data = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/CSC325/Project/a.us.txt')

"""#Select Data Parameters#"""

X = data[['Open', 'High', 'Low']]

X.head()

y = data['Close']

y.head()

"""#Split the data#"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=1)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

"""#Train the model#"""

from sklearn.linear_model import LinearRegression
lr_stocks = LinearRegression()
lr_stocks.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error
train_mse = mean_squared_error(y_train, lr_stocks.predict(X_train))
print('Training mse:', train_mse)

test_mse = mean_squared_error(y_test, lr_stocks.predict(X_test))
print('Test mse:', test_mse)

