# -*- coding: utf-8 -*-
"""SimpleLinearRegressionProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y4FB7tAoNrcqE9YmwmMg_yh107ksYtO9

#Import Libaries
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

"""#Define and Format Data"""

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/Stocks/CSV/afk.us.csv')
X = data[['Open']]
y = data[['Close']]
data.head()

X.head()

y.head()

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

"""#Train Model and Test Performance"""

lr = LinearRegression()
lr.fit(X_train, y_train)

y_train_predict = lr.predict(X_train)
train_mse = mean_squared_error(y_train, y_train_predict)
print('Training MSE: ', train_mse)

y_test_predict = lr.predict(X_test)
test_mse = mean_squared_error(y_test, y_test_predict)
print('Test MSE: ', test_mse)